<div>
    <h2>Dependency Example</h2>
</div>

<p>
    Class main id is <?= $block->getMain()->getId()  ?> 
</p>

<p>
    Class injectable id is <?= $block->getMain()->getInjectable()->getId() ?>
</p>
<p>
    Class non-Injectable id is <?= $block->getMain()->getNonInjectable()->getId() ?>
</p>
<p>
    Class util id is  <?= $block->getMain()->getUtil()->getName() ?>
</p>
<p>
    Class HeavyOperation is <?= $block->getMain()->getHeavyOperation()->getName() ?>
</p>
<p>
    Class DefaultName is <?= $block->getMain()->getDefaultName()->getName() ?>
</p>
<p>
    Class Optional Name is <?= $block->getMain()->getOptional()->getName() ?>
</p>

<p>
    Class Method Injection Name is <?= $block->getMain()->getMethodInjectionName()?>
</p>