<?php /** @var \Training\LayoutExample\Block\Layout\Index $block */ ?>
<h2><?=$block->getSubTitle() ?></h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci animi mollitia porro eligendi ut necessitatibus, dolore deserunt recusandae laborum neque nihil natus quisquam nam est perspiciatis minima quos, beatae laboriosam!</p>
<?= $block->getChildHtml('layout_note' ) ?>

<?= $block->getNodeHtml() ?>
<?= $block->getChildHtml('cms_block_example') ?> 